server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost/emason-transaction
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        security: TRACE